export const huntData = [
  {
    huntId: 1,
    huntName: "Find Mickey",
    expiryDate: "2024-12-31",
    image: "/images/mickey.png",
    color: "#FFC022",
    utilityOne: "Free Entry to Disneyland",
    utilityTwo: "20% Off at Disney Store",
    location: "Disneyland Park, Paris",
    huntDescription: "Solve the clues to win free goodies at your loved spot",
  },
  {
    huntId: 2,
    huntName: "H&M's Hunt",
    expiryDate: "2025-01-15",
    image: "/images/hm.png",
    color: "#FB4912",
    utilityOne: "30% Off on Apparel",
    utilityTwo: "Special Access to Sales",
    location: "H&M Store, New York",
    huntDescription: "Find hidden treasures in the latest collections",
  },
  {
    huntId: 3,
    huntName: "Where iPhone",
    expiryDate: "2024-11-20",
    image: "/images/apple.png",
    color: "#FCFCFC",
    utilityOne: "Early Access to iPhone",
    utilityTwo: "Exclusive Apple Merchandise",
    location: "Apple Store, Cupertino",
    huntDescription: "Discover the secrets of the latest Apple technology",
  },
  {
    huntId: 4,
    huntName: "McD's Special",
    expiryDate: "2024-10-31",
    image: "/images/mcd.png",
    color: "#FEC7C7",
    utilityOne: "Free Happy Meal",
    utilityTwo: "Buy One Get One Free Burger",
    location: "McDonald's, Chicago",
    huntDescription: "Uncover tasty treats in a fun-filled burger hunt",
  },
  {
    huntId: 5,
    huntName: "Coffee Fiesta",
    expiryDate: "2024-12-10",
    image: "/images/starbucks.png",
    color: "#F091F9",
    utilityOne: "Free Custom Drink",
    utilityTwo: "20% Off on Merchandise",
    location: "Starbucks, Seattle",
    huntDescription: "Embark on a journey to discover unique coffee",
  },
];
